version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-basics"
#s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kovbgtttmlha"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kovbgtttmlha"
s3_prefix = "lambda-basics"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
